sudo: required
dist: trusty
language: python
python:
  - "2.7"
env:
  - PYBOSSA_SETTINGS='../settings_test.py' PYBOSSA_REDIS_CACHE_DISABLED='1' PYBOSSA_PATH='./pybossa'
services:
  - redis-server
addons:
  postgresql: "9.5"
before_install:
  - sudo apt-get update -y && sudo apt-get install -y swig libffi-dev
  - pip install -U pip
install:
  - git clone --recursive https://github.com/PyBossa/pybossa.git
  - cd pybossa
  - pip install -r requirements.txt
  - cd ..
  - pip install --editable pybossa
  - pip install -r test_requirements.txt
before_script:
  - redis-server pybossa/contrib/redis/sentinel.conf --sentinel
  - psql -c "create user rtester with createdb login password 'rtester'" -U postgres
  - psql -c "create database pybossa_test owner rtester encoding 'UTF-8' lc_collate 'en_US.UTF-8' lc_ctype 'en_US.UTF-8' template template0;" -U postgres
  - pycodestyle
script:
  - cd pybossa
  - alembic -c alembictest.ini stamp head
  - alembic -c alembictest.ini upgrade head
  - cd ..
  - nosetests test/
after_success:
  - pip install coveralls
  - coveralls
